### ISSUE TITLE
Design, implement models

### ISSUE THREAD

**Issue by gabrielkrell** [mmking2048/UX2017#12]
I installed VS and have been poking around.  As far as I can tell, the best place to put #9, methods to query the API and create DTOs, will be inside the definitions of those classes in Models.

To-do:
- [ ] Add DTOs (equivalent to domain models in this case?):
    - [ ] Profile and Financial Data
    - [ ] Splits, Dividends, and Earnings
    - [ ] News and Filings
- [ ] Add utility functions to initialize DTOs from JSON.
- [ ] Add utility functions to generate API calls from parameters (see existing libs).

My first instinct was to put these as utility methods in some file since creating a DTO shouldn't depend on current context, but it seems like this is an anti-pattern in MVC.

@mmking2048, what are your thoughts on how we'll organize this data?  I assume that we'll need some kind of a database to store finished articles and avoid duplicate API calls.  I'm wondering whether we should store the API results/DTOs directly, or store them in a different way (for instance, organizing results by company instead of by API call).

**Comment by mmking2048** [comment]
My thoughts:

- For the API, start with the ones in the Profile and Financial Data; Splits, Dividends, and Earnings; and News and Filings.
- First, create DTOs, which are just purely the objects
- Then create a utility class with methods to fetch data. It should fetch JSON and pass to parsing class. Each method should have expected inputs per the API documentation.
- Create another utility class with methods to parse JSON and initialize object.

You should end up with a lot of DTOs, not just one or two.

For now we can ignore the database storing and do the generation as needed. I'll write up a card for it.

Let me know if you need more clarifications.

**Comment by gabrielkrell** [comment]
Cool, thanks for the help.  I think planning to do it on the fly will make things much easier.

**Comment by gabrielkrell** [comment]
One more question: I haven't dealt with high-level static-typed languages in a while and am wondering about the DTO implementation.  I did some text processing (hooray for multiline editing) on the Price Data > Quote API earlier to make a [class](https://github.com/mmking2048/UX2017/blob/issue/12/UX2017/Models/Quote.cs) out of it, resulting in objects with a property for each possible output field from the API.  Trouble is, the API calls are pretty large and this results in a lot of boilerplate.

In Python I'd just put the optional fields into a dictionary, but in C# dicts need a single value type.  Rather than make one dict for every type (gross), do you know a way to do it and avoid all the blah code?

**Comment by mmking2048** [comment]
I think it's fine to leave it as is. I'm not sure what you mean by "put optional fields into a dictionary", but if that's what you really want to do, use a dictionary of type object.

**Comment by gabrielkrell** [comment]
In Python/Flask I'd add each optional properties to the object's internal
dictionary as `propertyname: value` to avoid including all the possible
properties in code as fields.  I don't want to use an object dictionary
because then you need external logic to cast the values. I'll go ahead in
the current style (and automate as much as possible); I just wanted to
confirm before adding so many lines of code.

On Oct 7, 2017 6:16 PM, "mmking2048" <notifications@github.com> wrote:

I think it's fine to leave it as is. I'm not sure what you mean by "put
optional fields into a dictionary", but if that's what you really want to
do, use a dictionary of type object.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mmking2048/UX2017/issues/12#issuecomment-334971927>,
or mute
the thread
