### ISSUE TITLE
Add "Sane GitHub Labels"

### ISSUE THREAD

**Issue by gabrielkrell** [mmking2048/UX2017#13]
I like labels in the style of ["Sane GitHub Labels"](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63) where we have type/priority/status categories of labels, and each issue gets max one label from each category.  Since we're using Projects to track issues I think we can trim down the status labels.

I'd like to replace the default labels with:
 - `Type: Bug`
 - `Type: Enhancement`
 - `Type: Maintenance`
 - `Type: Question`
 - `Priority: Critical`
 - `Priority: High`
 - `Priority: Medium`
 - `Priority: Low`
 - `Status: Blocked`
 - `Status: Review Needed`
 - `Status: Wontfix`

The linked Medium post also has a tool to add labels automatically, since it takes a while to do on GitHub itself.

@mmking2048, since you have settings access, would you take a look at this and see what you think?

**Comment by mmking2048** [comment]
Done
